### ISSUE TITLE
Please remove the static Footer Text

### ISSUE THREAD

**Issue by prithwirajbose** [StefanLiebenberg/html-exception-formatter#1]
The static footer makes no sense. The HTML Stacktrace should no how contain the credit footer. In fact this single feature discards all credibility of this lib to be used for enterprise usage purpose. Please remove it.

_Message generated at 2020-04-13T19:52:12.893 by Html Exception Formatter._

**Comment by StefanLiebenberg** [comment]
You can use:

```java
options.setPrintFooter(false);
```
or 

```java
options.setPromoteLibrary(false);
```
